version: "3.9"

services:
  perlite:
    image: perlite-auth-app
    container_name: perlite-auth-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # username&pass
      - PERLITE_USERNAME=admin
      - PERLITE_PASSWORD=admin

      # Perlite env
      - NOTES_PATH=Obsidian
      - HIDE_FOLDERS=docs,private,trash
      - HIDDEN_FILE_ACCESS=false
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=true
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=false
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Perlite
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Perlite Auth
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=http://domain.example
    volumes:
      - ./perlite/Obsidian:/var/www/perlite/Obsidian:ro
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
